### ISSUE TITLE
Keep user logged in

### ISSUE THREAD

**Issue by danielwildsmith** [skirill430/Quick-Shop#43]
I believe this can be done using a HTTP cookie and jwt.

**Comment by danielwildsmith** [comment]
i think we will be able to store the username within the cookie, so it can be accessible when trying to save/remove a product when logged in.

**Comment by csobolew** [comment]
I was thinking maybe the backend takes the username and password and then generates a unique ID for the session that it stores, and that's what's included in the cookie? Storing username/password in the cookie seems insecure.

**Comment by danielwildsmith** [comment]
yeah that's a good idea, i'll look into it.

**Comment by danielwildsmith** [comment]
https://www.sohamkamani.com/golang/jwt-authentication/

This link has a good example of using the jwt token as an ID within a cookie.

**Comment by csobolew** [comment]
Yeah that looks really good
